version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - pgadmin-network

networks:
  pgadmin-network:
    driver: bridge
